services:
  db:

    # Image and container
    image: postgres:15
    container_name: db_container

    # Configuration: credentials, ports and volume
    # restart: always
    environment:
      POSTGRES_USER: example  
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sales

    ports:
      - "8090:5432"
    volumes:
      - ./initial_data.sql:/docker-entrypoint-initdb.d/init.sql